plugins:
  - jekyll-seo-tag

title: Trident Designs
tagline: Artisanal handcrafted epoxy and wood designs.
description: Artisanal handcrafted epoxy and wood designs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.tridentdesigns.co.za" # the base hostname & protocol for your site, e.g. http://example.com
logo: /assets/img/logo.png

author: Trident Designs

email: info@tridentdesigns.co.za
phone: +27 82 486 7918

facebook:
  username: TridentDesignsZA
  publisher: TridentDesignsZA

instagram:
  username: tridentdesignsza

whatsapp:
  number: 27824867918

social:
  name: Trident Designs
  links:
    - https://www.facebook.com/TridentDesignsZA
    - https://www.instagram.com/tridentdesignsza

locale: en_ZA

google_site_verification: 
google_analytics: 